### ISSUE TITLE
Console Command Execution Causes ClassCastException

### ISSUE THREAD

**Issue by Cirkutry** [Imhhitt/FancyGlow#8]
>Description:

When attempting to execute commands such as `glow reload` or `glow disable <player>` from the console, the following error occurs: https://rentry.org/23hoxihq

>Expected Behavior:

The command should execute properly in the console without requiring a player as the sender.

>Actual Behavior:

A ClassCastException is thrown, causing the command to fail.

> Environment:

    Minecraft version: 1.21.1
    Paper version: 1.21.1-DEV-2fdb2e9
    FancyGlow version: 2.2.0
    Java version: Java 21

>Proposed Solution:

Modify the command handler to check if the sender is an instance of Player before casting. For console commands, handle TerminalConsoleCommandSender appropriately.

Best,
C.K.

**Comment by Imhhitt** [comment]
hi, fixed!
thank u.
