### ISSUE TITLE
Only glows White

### ISSUE THREAD

**Issue by AwesomeKalin** [Imhhitt/FancyGlow#9]
When selecting any colour, it only glows white. Any way I can fix it, or is this a bug with the plugin? Running paper 1.21.1. Thanks in advance

**Comment by Imhhitt** [comment]
Hi! Did u add the placeholder in TAB's groups.yml and enabled unlimited-tag-mode as mentioned in plugin documentation?

**Comment by AwesomeKalin** [comment]
Didn't change anything

**Comment by Imhhitt** [comment]
Send here ur config.yml and groups.yml from TAB plugin
